# Use the official Node.js image
FROM node:16.20.2

# Set the working directory
WORKDIR /opt/app

# Copy the package.json and package-lock.json files to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the entire project to the working directory
COPY . .

# Run the build step (adjust the command based on your project's build script)
RUN npm run build

COPY .next ./_next
COPY public ./public

# Specify the command to run your application (adjust based on your project)
CMD ["npm", "run", "dev"]
