# Указываем базовый образ
FROM node:16-alpine as build

# Устанавливаем переменные среды
ENV NODE_ENV=production

# Устанавливаем рабочую директорию
WORKDIR /opt/app

# Копируем файлы зависимостей
COPY package.json package-lock.json ./

# Устанавливаем зависимости
RUN npm install --only=production

# Копируем исходный код
COPY . .

# Запускаем сборку
RUN npm run build

# Создаем финальный образ
FROM node:18-alpine

# Устанавливаем рабочую директорию
WORKDIR /opt/app

# Копируем сборку и зависимости из предыдущего шага
COPY --from=build /opt/app ./

# Указываем, какой пользователь будет использоваться
USER node

# Указываем порт
EXPOSE 1337

# Запускаем приложение
CMD ["npm", "run", "start"]
