FROM node:20.18.0-alpine as build

RUN apk update && apk add --no-cache build-base zlib-dev libpng-dev vips-dev git

WORKDIR /opt/app

COPY package.json package-lock.json ./

RUN npm install --only=production

COPY . .

RUN npm run build

FROM node:20.18.0-alpine

RUN apk add --no-cache vips-dev

WORKDIR /opt/app

COPY --from=build /opt/app ./

USER node

EXPOSE 1337

CMD ["npm", "run", "start"]
