version: '3.9'

services:
  client:
    build:
      context: ../client
      dockerfile: ../client/dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server-cms
    environment:
      - NEXT_PUBLIC_API_URL=http://server-cms:1337
    restart: unless-stopped
    networks:
      - app-network

  server-cms:
    build:
      context: ../server-cms
      dockerfile: ../server-cms/dockerfile
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=production
      - TZ=Europe/Kyiv
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
